### PR TITLE
refactor, add mmap based ring buffer

### PR DESCRIPTION
**Pull request by sleepybishop**
thank you for creating this project, it was very useful to me. if youre still mantaining it i made some improvements, notably reducing external dependencies by linking against libhdhomerun directly and using an mmap based ring buffer.

### CODE REVIEW

**Comment by malahal** [comment]
This is the first time anyone made any comment on this! I made for my "WDTV
Live" media player but it was a bit tricky to work with it. I sold my unit
a while back and replaced with ASUS chromebox that runs full linux. I will
try to merge your changes, also I will make you an admin.

Just curious, what hardware are you running this?

Regards, Malahal.

**Comment by sleepybishop** [comment]
i recently centralized all my storage to a box running an asrock c2750. it runs fedora with nfs and dlna/upnp servers for the various devices around the house to access.

best,

--joe

**Comment by malahal** [comment]
Hi Joe, I made you as a collaborator, so you should be able to push things into the repo directly. I also merged your changes in to "dev" branch (not master branch yet).  If you think things are stable, please update the master branch.

I had issues with "WDTV Live" due to its proprietary player.  This latest code doesn't work with what it was used for, but I am fine as that player is history now!

can you please add a README file in dep/mmapring? Are they your own creation or taken from some other project?

**Comment by sleepybishop** [comment]
its my own implementation of a common approach, i added a readme with more info and similar implementations. i think ill close this pr and create a new one under the dev branch.

**Pull request closed without merging**
